// $ANTLR 2.7.6 (2005-12-22): "grammar.g" -> "LeLexer.java"$

public interface LeParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int LITERAL_program = 4;
	int ID = 5;
	// "{" = 6
	// "}" = 7
	int VG = 8;
	int PV = 9;
	int LITERAL_cte = 10;
	int LITERAL_int = 11;
	int LITERAL_decimal = 12;
	int LITERAL_str = 13;
	int LITERAL_bool = 14;
	int IG = 15;
	int TEXTO = 16;
	int LITERAL_Read = 17;
	// "(" = 18
	// ")" = 19
	int LITERAL_Write = 20;
	int TEXT = 21;
	int LITERAL_if = 22;
	int LITERAL_endif = 23;
	int LITERAL_for = 24;
	int AP = 25;
	int NUM = 26;
	// ":" = 27
	int FP = 28;
	int LITERAL_nextfor = 29;
	int LITERAL_while = 30;
	int OPLOG = 31;
	int OPREL = 32;
	int LITERAL_true = 33;
	int LITERAL_false = 34;
	// "str.Concat" = 35
	int OP = 36;
	int BLANK = 37;
	int COMMENT = 38;
	int AC = 39;
	int FC = 40;
}
