// $ANTLR 2.7.6 (2005-12-22): "grammar.g" -> "LeLexer.java"$

public interface LeParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int LITERAL_program = 4;
	int ID = 5;
	// "{" = 6
	// "}" = 7
	int VG = 8;
	int PV = 9;
	int LITERAL_cte = 10;
	int LITERAL_int = 11;
	int LITERAL_decimal = 12;
	int LITERAL_str = 13;
	int LITERAL_bool = 14;
	int IG = 15;
	int LITERAL_Read = 16;
	// "(" = 17
	// ")" = 18
	int LITERAL_Write = 19;
	int TEXTO = 20;
	int LITERAL_if = 21;
	int LITERAL_else = 22;
	int LITERAL_endif = 23;
	int LITERAL_while = 24;
	int LITERAL_next = 25;
	int OPLOG = 26;
	int OPREL = 27;
	int OP = 28;
	int NUM = 29;
	int LITERAL_true = 30;
	int LITERAL_false = 31;
	int BLANK = 32;
	int COMMENT = 33;
	int AC = 34;
	int FC = 35;
	int AP = 36;
	int FP = 37;
}
